using Microsoft.AspNetCore.Mvc;
using mascotas.Models;

namespace mascotas.Controllers
{
    public class DogController : Controller
    {
        public IActionResult Index()
        {
            var dogs = GetDogList();
            return View(dogs);
        }

        private List<Dog> GetDogList()
        {
            return new List<Dog>
            {
                new Dog { Name = "Akita Inu", Category = "A", Weight = "32-59 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Beagle", Category = "B", Weight = "9-11 kg", Size = "Mediano", Lifespan = 13 },
                new Dog { Name = "Bulldog Inglés", Category = "B", Weight = "18-23 kg", Size = "Mediano", Lifespan = 9 },
                new Dog { Name = "Border Collie", Category = "B", Weight = "14-20 kg", Size = "Mediano", Lifespan = 12 },
                new Dog { Name = "Boston Terrier", Category = "B", Weight = "4-11 kg", Size = "Pequeño", Lifespan = 13 },
                new Dog { Name = "Cocker Spaniel", Category = "C", Weight = "12-16 kg", Size = "Mediano", Lifespan = 13 },
                new Dog { Name = "Chihuahua", Category = "C", Weight = "1.5-3 kg", Size = "Pequeño", Lifespan = 15 },
                new Dog { Name = "Chow Chow", Category = "C", Weight = "20-32 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Dálmata", Category = "D", Weight = "20-27 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Doberman", Category = "D", Weight = "27-45 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Golden Retriever", Category = "G", Weight = "25-34 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Husky Siberiano", Category = "H", Weight = "16-27 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Labrador Retriever", Category = "L", Weight = "25-36 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Mastín Español", Category = "M", Weight = "50-90 kg", Size = "Gigante", Lifespan = 10 },
                new Dog { Name = "Pastor Alemán", Category = "P", Weight = "22-40 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Pastor Belga Malinois", Category = "P", Weight = "18-30 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Pastor Australiano", Category = "P", Weight = "18-29 kg", Size = "Mediano", Lifespan = 13 },
                new Dog { Name = "Perro Crestado Chino", Category = "P", Weight = "2-5 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Pomerania", Category = "P", Weight = "1.5-3.5 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Pug", Category = "P", Weight = "6-8 kg", Size = "Pequeño", Lifespan = 13 },
                new Dog { Name = "Rottweiler", Category = "R", Weight = "35-60 kg", Size = "Grande", Lifespan = 10 },
                new Dog { Name = "Samoyedo", Category = "S", Weight = "20-30 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "San Bernardo", Category = "S", Weight = "54-82 kg", Size = "Gigante", Lifespan = 9 },
                new Dog { Name = "Shih Tzu", Category = "S", Weight = "4-7 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Schnauzer Miniatura", Category = "S", Weight = "5-9 kg", Size = "Pequeño", Lifespan = 13 },
                new Dog { Name = "Schnauzer Gigante", Category = "S", Weight = "25-48 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Setter Inglés", Category = "S", Weight = "20-36 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Setter Irlandés", Category = "S", Weight = "25-32 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Shar Pei", Category = "S", Weight = "18-25 kg", Size = "Mediano", Lifespan = 12 },
                new Dog { Name = "Weimaraner", Category = "W", Weight = "25-40 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Yorkshire Terrier", Category = "Y", Weight = "2-3.5 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Akita Inu", Category = "A", Weight = "32-59 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Beagle", Category = "B", Weight = "9-11 kg", Size = "Mediano", Lifespan = 13 },
                new Dog { Name = "Bulldog Inglés", Category = "B", Weight = "18-23 kg", Size = "Mediano", Lifespan = 9 },
                new Dog { Name = "Border Collie", Category = "B", Weight = "14-20 kg", Size = "Mediano", Lifespan = 12 },
                new Dog { Name = "Boston Terrier", Category = "B", Weight = "4-11 kg", Size = "Pequeño", Lifespan = 13 },
                new Dog { Name = "Cocker Spaniel", Category = "C", Weight = "12-16 kg", Size = "Mediano", Lifespan = 13 },
                new Dog { Name = "Chihuahua", Category = "C", Weight = "1.5-3 kg", Size = "Pequeño", Lifespan = 15 },
                new Dog { Name = "Chow Chow", Category = "C", Weight = "20-32 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Dálmata", Category = "D", Weight = "20-27 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Doberman", Category = "D", Weight = "27-45 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Golden Retriever", Category = "G", Weight = "25-34 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Husky Siberiano", Category = "H", Weight = "16-27 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Labrador Retriever", Category = "L", Weight = "25-36 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Mastín Español", Category = "M", Weight = "50-90 kg", Size = "Gigante", Lifespan = 10 },
                new Dog { Name = "Pastor Alemán", Category = "P", Weight = "22-40 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Pastor Belga Malinois", Category = "P", Weight = "18-30 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Pastor Australiano", Category = "P", Weight = "18-29 kg", Size = "Mediano", Lifespan = 13 },
                new Dog { Name = "Perro Crestado Chino", Category = "P", Weight = "2-5 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Pomerania", Category = "P", Weight = "1.5-3.5 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Pug", Category = "P", Weight = "6-8 kg", Size = "Pequeño", Lifespan = 13 },
                new Dog { Name = "Rottweiler", Category = "R", Weight = "35-60 kg", Size = "Grande", Lifespan = 10 },
                new Dog { Name = "Samoyedo", Category = "S", Weight = "20-30 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "San Bernardo", Category = "S", Weight = "54-82 kg", Size = "Gigante", Lifespan = 9 },
                new Dog { Name = "Shih Tzu", Category = "S", Weight = "4-7 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Schnauzer Miniatura", Category = "S", Weight = "5-9 kg", Size = "Pequeño", Lifespan = 13 },
                new Dog { Name = "Schnauzer Gigante", Category = "S", Weight = "25-48 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Setter Inglés", Category = "S", Weight = "20-36 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Setter Irlandés", Category = "S", Weight = "25-32 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Shar Pei", Category = "S", Weight = "18-25 kg", Size = "Mediano", Lifespan = 12 },
                new Dog { Name = "Weimaraner", Category = "W", Weight = "25-40 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Yorkshire Terrier", Category = "Y", Weight = "2-3.5 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Akita Inu", Category = "A", Weight = "32-59 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Beagle", Category = "B", Weight = "9-11 kg", Size = "Mediano", Lifespan = 13 },
                new Dog { Name = "Bulldog Inglés", Category = "B", Weight = "18-23 kg", Size = "Mediano", Lifespan = 9 },
                new Dog { Name = "Border Collie", Category = "B", Weight = "14-20 kg", Size = "Mediano", Lifespan = 12 },
                new Dog { Name = "Boston Terrier", Category = "B", Weight = "4-11 kg", Size = "Pequeño", Lifespan = 13 },
                new Dog { Name = "Cocker Spaniel", Category = "C", Weight = "12-16 kg", Size = "Mediano", Lifespan = 13 },
                new Dog { Name = "Chihuahua", Category = "C", Weight = "1.5-3 kg", Size = "Pequeño", Lifespan = 15 },
                new Dog { Name = "Chow Chow", Category = "C", Weight = "20-32 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Dálmata", Category = "D", Weight = "20-27 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Doberman", Category = "D", Weight = "27-45 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Golden Retriever", Category = "G", Weight = "25-34 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Husky Siberiano", Category = "H", Weight = "16-27 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Labrador Retriever", Category = "L", Weight = "25-36 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Mastín Español", Category = "M", Weight = "50-90 kg", Size = "Gigante", Lifespan = 10 },
                new Dog { Name = "Pastor Alemán", Category = "P", Weight = "22-40 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Pastor Belga Malinois", Category = "P", Weight = "18-30 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Pastor Australiano", Category = "P", Weight = "18-29 kg", Size = "Mediano", Lifespan = 13 },
                new Dog { Name = "Perro Crestado Chino", Category = "P", Weight = "2-5 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Pomerania", Category = "P", Weight = "1.5-3.5 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Pug", Category = "P", Weight = "6-8 kg", Size = "Pequeño", Lifespan = 13 },
                new Dog { Name = "Rottweiler", Category = "R", Weight = "35-60 kg", Size = "Grande", Lifespan = 10 },
                new Dog { Name = "Samoyedo", Category = "S", Weight = "20-30 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "San Bernardo", Category = "S", Weight = "54-82 kg", Size = "Gigante", Lifespan = 9 },
                new Dog { Name = "Shih Tzu", Category = "S", Weight = "4-7 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Schnauzer Miniatura", Category = "S", Weight = "5-9 kg", Size = "Pequeño", Lifespan = 13 },
                new Dog { Name = "Schnauzer Gigante", Category = "S", Weight = "25-48 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Setter Inglés", Category = "S", Weight = "20-36 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Setter Irlandés", Category = "S", Weight = "25-32 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Shar Pei", Category = "S", Weight = "18-25 kg", Size = "Mediano", Lifespan = 12 },
                new Dog { Name = "Weimaraner", Category = "W", Weight = "25-40 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Yorkshire Terrier", Category = "Y", Weight = "2-3.5 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Akita Inu", Category = "A", Weight = "32-59 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Beagle", Category = "B", Weight = "9-11 kg", Size = "Mediano", Lifespan = 13 },
                new Dog { Name = "Bulldog Inglés", Category = "B", Weight = "18-23 kg", Size = "Mediano", Lifespan = 9 },
                new Dog { Name = "Border Collie", Category = "B", Weight = "14-20 kg", Size = "Mediano", Lifespan = 12 },
                new Dog { Name = "Boston Terrier", Category = "B", Weight = "4-11 kg", Size = "Pequeño", Lifespan = 13 },
                new Dog { Name = "Cocker Spaniel", Category = "C", Weight = "12-16 kg", Size = "Mediano", Lifespan = 13 },
                new Dog { Name = "Chihuahua", Category = "C", Weight = "1.5-3 kg", Size = "Pequeño", Lifespan = 15 },
                new Dog { Name = "Chow Chow", Category = "C", Weight = "20-32 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Dálmata", Category = "D", Weight = "20-27 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Doberman", Category = "D", Weight = "27-45 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Golden Retriever", Category = "G", Weight = "25-34 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Husky Siberiano", Category = "H", Weight = "16-27 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Labrador Retriever", Category = "L", Weight = "25-36 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Mastín Español", Category = "M", Weight = "50-90 kg", Size = "Gigante", Lifespan = 10 },
                new Dog { Name = "Pastor Alemán", Category = "P", Weight = "22-40 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Pastor Belga Malinois", Category = "P", Weight = "18-30 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Pastor Australiano", Category = "P", Weight = "18-29 kg", Size = "Mediano", Lifespan = 13 },
                new Dog { Name = "Perro Crestado Chino", Category = "P", Weight = "2-5 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Pomerania", Category = "P", Weight = "1.5-3.5 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Pug", Category = "P", Weight = "6-8 kg", Size = "Pequeño", Lifespan = 13 },
                new Dog { Name = "Rottweiler", Category = "R", Weight = "35-60 kg", Size = "Grande", Lifespan = 10 },
                new Dog { Name = "Samoyedo", Category = "S", Weight = "20-30 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "San Bernardo", Category = "S", Weight = "54-82 kg", Size = "Gigante", Lifespan = 9 },
                new Dog { Name = "Shih Tzu", Category = "S", Weight = "4-7 kg", Size = "Pequeño", Lifespan = 14 },
                new Dog { Name = "Schnauzer Miniatura", Category = "S", Weight = "5-9 kg", Size = "Pequeño", Lifespan = 13 },
                new Dog { Name = "Schnauzer Gigante", Category = "S", Weight = "25-48 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Setter Inglés", Category = "S", Weight = "20-36 kg", Size = "Grande", Lifespan = 12 },
                new Dog { Name = "Setter Irlandés", Category = "S", Weight = "25-32 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Shar Pei", Category = "S", Weight = "18-25 kg", Size = "Mediano", Lifespan = 12 },
                new Dog { Name = "Weimaraner", Category = "W", Weight = "25-40 kg", Size = "Grande", Lifespan = 13 },
                new Dog { Name = "Yorkshire Terrier", Category = "Y", Weight = "2-3.5 kg", Size = "Pequeño", Lifespan = 14 },
            };
        }
    }
}

